--- 
clone: 
  depth: 1
kind: pipeline
name: NetErnels-RMX2020-Pipeline
steps: 
  - name: Kernel Pipeline
    image: panchajanya1999/archlinux:latest
    commands: 
      - pacman -Syu --needed --noconfirm wget base-devel xmlto inetutils bc cpio python-sphinx python-sphinx_rtd_theme graphviz imagemagick git python2 python zip unzip
      - "export token=$TOKEN"
      - "bash kramel-build.sh"
    environment: 
      TOKEN: 
        from_secret: token

trigger:
  event:
  - custom
