--- 
clone: 
  depth: 1
kind: pipeline
name: NetErnels-RMX2020-Pipeline
steps: 
  - name: Kernel Pipeline
    image: panchajanya1999/archlinux:latest
    commands: 
      - "export token=$TOKEN"
      - "bash kramel-build.sh"
    environment: 
      TOKEN: 
        from_secret: token

trigger:
  event:
  - custom
